name: pkb_no_screenshots
description: A new Flutter package no screenshots.
version: 1.0.0
homepage: https://github.com/pirapong/pkb_no_screenshots

#environment:
#  sdk: '>=3.1.0 <4.0.0'
#  flutter: ">=1.17.0"
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pkb.no_screenshot
        pluginClass: NoScreenshotPlugin
#      ios:
#        pluginClass: NoScreenshotPlugin
